spring:
  profiles:
    active: secret
  data:
    mongodb:
      uri: ${MONGODB_URI}
  output:
    ansi:
      enabled: always
  mvc:
    async:
      request-timeout: -1
jackson:
  serialization:
    indent-output: true